project:
  type: website
  output-dir: docs

website:
  title: "Alayna Rowell"
  navbar:
    logo: "AR_logo.png"
    left:
      - text: "CV"
        href: about.qmd
      - text: "Research"
        href: research.qmd
      - text: "Blog" 
        href: blog.qmd
    right: 
    - icon: linkedin
      text: LinkedIn
      href: https://www.linkedin.com/in/alayna-rowell-915097236
    - icon: envelope
      text: Email
      href: "mailto:alayna.rowell@case.edu"
  sidebar:
    style: "docked"
    search: true
  page-footer: 
    left: "Website created by Alayna Rowell, via Quarto. Images created in BioRender" 
    right:  
    - icon: linkedin
      text: LinkedIn
      href: www.linkedin.com/in/alayna-rowell-915097236
    - icon: envelope
      text: Email
      href: "mailto:alayna.rowell@case.edu"

format:
  html:
    theme: lux
    css: styles.css
    toc: true

editor: visual
  


