---
title: "Blog"
---

### 2025-24-03

With this blog, I plan to follow Jeff Leek's advice in  *How To Be A Modern Scientist* . He recommends using a scientific blog to:

• Show off storytelling or communication skills,

• Show off data visualization skills,

• Teach people how to do some kind of analysis, and

• Discuss important issues that are relevant in my industry.

My field of clinical practice and research is often silo-ed, and so finding ways to translate findings from inside the field to those outside of it, and vice versa, will be a large part of my future career. A key theme of  *How To Be A Modern Scientist*  emphasizes the role that new technology can play in research while maintaining rigor and transparency. Further, Jeff Leek argues that new technology cannot just be used, it must also be easy to understand and access. This aligns with my personal goals; as researchers, we can embrace change and integrate new tools for betterment of knowledge sharing and efficiency. An example of a new platform I learned at the beginning of my research program is Slack, which Jeff Leek discusses in relevance to internal scientific communication. In reference to content aimed at external audiences, a tangible way to make content more approachable is to 'entertain' rather than teach; indeed, all of my favorite instructors have been conversational in their approach rather than dogmatic. I appreciate the perspective that Jeff Leek offers, and I aim to use the advice in his book to reach fellow providers, community members, and researchers of different backgrounds when I speak about my research.
